Config = {}
Config.token = "Token_Twojego_Bota" --https://discord.com/developers/applications/
Config.webhook = "WEBHOOK_PRYWATNEGO_KANAŁU"
Config.id_kanału = "ID_PRYWATNEGO_KANAŁU"
Config.Nazwa = "NAZWA_WEBHOOKA"
Config.Prefix = "Prefix_Bota"
Config.WaitEveryTick = 4000  -- Czas W MS
Config.kick = true
Config.revive = true
Config.setjob = true
Config.announce = true